# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86cae011fb88d1c52d32d144b9f195543e0892e91e037e0b568a97248356bb629120e13834474d0c868e416aaa23cbe5ef18203fed796429b341dc75574c0f32

test:
  secret_key_base: 05121bf104ccea8a97ebfa775ea8b812c04ac92c97b88e32d2108e54e42ccae91e4fcccdd204aa421b95383b394a0bd4c74c90aac864b7d8f8c8ab7b6c1f4896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
